---
# Small playbook to print data
- hosts: all
  gather_facts: no
  become: no
  tasks:
    - name: Include the generated vault data
      include_vars:
        file: vault_data.yml

    - name: Print host_data for host
      debug: msg="Encrypted data = {{ example_variable_name }}"
#      delegate_to: 127.0.0.1
#      become: no
